export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"

export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART"

export const UPDATE_STOCK = "UPDATE_STOCK"

export const EMPTY_CART = "EMPTY_CART"

export const SET_STOCK_BACK = "SET_STOCK_BACK"

